---
- name: determine directory name for font family
  set_fact:
    nerdfonts_font_family_dir: "{{ font|regex_replace('^([^/]+)/.*$', '\\1') }}"

- name: create directory for {{ nerdfonts_font_family_dir }} fonts
  file:
    owner: "{{ fonts_user }}"
    group: "{{ fonts_group }}"
    path: "{{ nerdfonts_directory }}/{{ nerdfonts_font_family_dir }}"
    state: directory

- name: download {{ font|basename }}
  get_url:
    dest: "{{ nerdfonts_directory }}/{{ nerdfonts_font_family_dir }}/{{ font|basename }}"
    owner: "{{ fonts_user }}"
    group: "{{ fonts_group|default(omit) }}"
    url: "{{ nerdfonts_github_raw_patched_fonts }}/{{ font | regex_replace(' ', '%20') }}"
